name: deploy-int

on:
  push:
    paths-ignore:
    - 'README.md'
    - '_documentation'
    branches: [ master ]

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

    - name: Install dependencies
      run: dotnet restore WebApi

    - name: Build artifact
      run: dotnet publish WebApi --configuration Release --no-restore

    - name: Stop the the WebApi
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          whoami
          systemctl stop tymish-int-kestrel.service

    - name: SCP to Digital Ocean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        source: "WebApi/bin/Release/net5.0/publish"
        strip_components: 5
        target: "${{ secrets.TARGET_PATH }}"
        rm: true
    
    - name: Start the api
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          systemctl start tymish-int-kestrel.service
          systemctl status tymish-int-kestrel.service
