name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore WebApi
    - name: Build artifact
      run: dotnet publish WebApi --configuration Release --no-restore
    - uses: actions/upload-artifact@v1
      with:
        name: tymish-api
        path: "WebApi/bin/Release/netcoreapp3.1/publish/"
   
  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v1
      with:
        name: tymish-api
        path: publish
    - name: SCP to Digital Ocean
      uses: appleboy/scp-action@v0.0.7
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.KEY }}
      with:
        source: "publish"
        target: "/var/www/tymish-api"
        rm: true

